
apiVersion: apps/v1
kind: Deployment

metadata:
  name: qwen-1-5b
  namespace: inference-dev
spec:
  replicas: 1

  selector:
    matchLabels:
      app: qwen-1-5b

  template:
    metadata:
      labels:
        app: qwen-1-5b

    spec:
      containers:
      - name: llama

        image: ghcr.io/ggml-org/llama.cpp:server

        command:
          - sh
          - -c
          - |
              mkdir -p /models && \
              curl -L -o /models/model.gguf https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf && \
              /app/llama-server \
                -m /models/model.gguf \
                --host 0.0.0.0 \
                --port 8080

        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"

          limits:
            memory: "2Gi"
            cpu: "1"
