
apiVersion: apps/v1
kind: Deployment

metadata:
  name: uploaded-model-test
  namespace: inference-dev
spec:
  replicas: 1

  selector:
    matchLabels:
      app: uploaded-model-test

  template:
    metadata:
      labels:
        app: uploaded-model-test

    spec:
      containers:
      - name: llama

        image: ghcr.io/ggml-org/llama.cpp:server

        command:
          - sh
          - -c
          - |
              mkdir -p /models && \
              curl -L -o /models/model.gguf https://huggingface.co/TheBloke/phi-2-GGUF/resolve/main/phi-2.Q2_K.gguf && \
              /app/llama-server \
                -m /models/model.gguf \
                --host 0.0.0.0 \
                --port 8080

        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"

          limits:
            memory: "2Gi"
            cpu: "1"
