resources:
  - ../../base
namespace: prod
nameSuffix: -prod

patches:
  - target:
      kind: Ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: fullstack.192.168.156.129.sslip.io
      
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: frontend-service-prod
      
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: backend-service-prod
