resources:
  - ../../base

namespace: platform
nameSuffix: -dev
patches:
  - target:
      kind: Ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev.platform-backend.136.119.144.166.sslip.io

      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: platform-backend-dev

      - op: replace
        path: /spec/rules/0/http/paths/1/backend/service/name
        value: platform-frontend-dev