resources:
  - ../../base

namespace: dev
nameSuffix: -dev

patches:
  - target:
      kind: Ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev.fullstack.192.168.156.129.sslip.io
      
      - op: replace
        path: /spec/rules/0/http/paths/0/frontend/service/name
        value: frontend-service-dev
      
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: backend-service-dev
