apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/thecrusader25225/application-services.git
    targetRevision: master
    path: environments/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

