
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-model2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-model2
  template:
    metadata:
      labels:
        app: test-model2
    spec:
      containers:
      - name: inference
        image: shane25225/inference-server:v3
        env:
        - name: MODEL_URL
          value: "https://storage.googleapis.com/models-bucket25225/models/best.onnx"
        ports:
        - containerPort: 8000
